name: Bagisto API Tests

on:
  push:
    branches: [ Bianca_Fernandez ]
  pull_request:
    branches: [ Bianca_Fernandez ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Start Bagisto container
        run: |
          echo "ðŸš€ Iniciando Bagisto..."
          docker run -d -p 8000:80 --name bagisto webkul/bagisto:2.3.0

      - name: Wait for Bagisto to be ready
        run: |
          echo "â³ Esperando que Bagisto estÃ© listo..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:8000); do
            printf '.'
            sleep 5
          done
          echo ""
          echo "âœ… Bagisto estÃ¡ en lÃ­nea."

      - name: Enable Bagisto REST API inside container
        run: |
          echo "âš™ï¸ Instalando REST API dentro del contenedor..."
          docker exec bagisto bash -c "
            cd /var/www/html && \
            composer require bagisto/rest-api && \
            echo 'SANCTUM_STATEFUL_DOMAINS=http://localhost:8000' >> .env && \
            php artisan bagisto-rest-api:install
          "
          echo "âœ… REST API instalada correctamente."

      - name: Run API Tests
        continue-on-error: true
        env:
          BASE_URL: http://localhost:8000/api/v1
        run: |
           pytest -v test/ -vvvv
      
      - name: Install Java for Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          java -version

      - name: Generate Allure Report
        run: |
          echo "Generando reporte de Allure..."
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report